---
version: "2"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/giz/sonarr/config:/config
      - /media/TvShows:/tv
      - /media/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
