---
version: "2.4"
services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
      - 8888:8888
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/ansible/unmanic/config:/config
      - /media/TvShows/:/library
      - /media/Movies/:/movies
      - /media/transcode:/tmp/unmanic
    restart: unless-stopped
