---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
        #      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - /home/ansible/jellyfin/config:/config
      - /media/TvShows:/data/tvshows
      - /media/Movies:/data/movies
      - /media/Musique:/data/music
#      - /media/backup/jellyfin/transcode:/transcode #optional
      - /home/ansible/jellyfin/config/transcode:/transcode
    ports:
      - 8097:8096
      - 8921:8920
    restart: unless-stopped
