---
version: "2"
services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    #    image: lscr.io/linuxserver/emby:4.7.6.0-ls127
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/ansible/emby/config:/config
      - /media/TvShows:/data/tvshows
      - /media/Movies:/data/movies
      - /home/ansible/emby/transcode:/transcode #optional
        #      - /home/ansible/emby/config/transcode:/transcode #optional
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped

