---
version: "2"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/ansible/radarr/config:/config
      - /media/Movies:/movies
      - /media/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
