version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name : navidrome
    user: 1000:1000 # should be owner of volumes
    volumes:
      - "/home/ansible/navidrome/config:/data"
      - "/media/Musique:/music:ro"
    ports:
      - "4533:4533"
    restart: unless-stopped
