---
version: "2.1"
services:
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/ansible/sabnzbd/config:/config
      - /media/downloads:/downloads
      - /media/downloads/temp:/incomplete-downloads
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped
